### PR TITLE
Don't use Signal () for ports (build fix 0.13)

### PR DESCRIPTION
**Pull request by kfish**
Using Signal () was never supported anyway according to the docs, and gives
a compile error with elm-0.13.

### CODE REVIEW

**Comment by evancz** [comment]
Does it work in 0.12.3? I think it is a regression if this is not working in 0.13.

**Comment by evancz** [comment]
My reasoning for documentation was that I see the unit value is a special case of tuples, a tuple with no entries. That's how it is represented in the compiler at least, though I see how it is not particularly intuitive.

In any case, do you think it should be more clearly stated in compiler errors or in documentation?

**Comment by kfish** [comment]
It works in 0.12.3, so yes this is a regression. (This is the pointerlock port code you wrote back in May, in the first commit of this project).

**Comment by kfish** [comment]
Ah, if you think () should work ok then this is definitely a regression.

Re: docs, I think it's useful for the compiler message and docs to specifically say that () is allowed -- I think of Signal () as an informationless impulse signal, not any kind of tuple.

**Comment by evancz** [comment]
Okay, the regression is fixed with this change https://github.com/elm-lang/Elm/commit/c8eeedf0f2f7cab265638b5272ce978ce2d63fde

I'll go around adding a note to error messages and online docs.

**Comment by evancz** [comment]
Thanks for pointing this out :)

**Pull request closed without merging**
